CREATE TABLE employee
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name   VARCHAR(100) NOT NULL,
    first_name  VARCHAR(100) NOT NULL,
    street      VARCHAR(100) NOT NULL,
    postal_code VARCHAR(50)  NOT NULL,
    city        VARCHAR(50)  NOT NULL
);

CREATE TABLE shipping_orders
(
    shipping_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id        UUID         NOT NULL UNIQUE,
    package_name      VARCHAR(100) NOT NULL UNIQUE,
    weight_in_grams   DOUBLE       NOT NULL CHECK (weight_in_grams > 0),
    receiver_emp_id   BIGINT       NOT NULL,
    sender_emp_id     BIGINT       NOT NULL,
    registration_date TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status            VARCHAR(50)  NOT NULL,
    delivered_date    TIMESTAMP,
    CONSTRAINT FK_SENDER_EMP_ID_CONSTRAINT
        FOREIGN KEY (sender_emp_id)
            REFERENCES employee (id),
    CONSTRAINT FK_RECEIVER_EMP_ID_CONSTRAINT
        FOREIGN KEY (receiver_emp_id)
            REFERENCES employee (id)
);

CREATE INDEX index_sender_emp_id ON shipping_orders (sender_emp_id);

CREATE SEQUENCE SHIPPING_ORDERS_SEQ START WITH 10000 INCREMENT BY 1;

