/*
 * Package Shipping Service
 * Service used to send packages to certain addresses.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.abnamro.packageshippingservice.model.response;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * OrderList
 */
@Setter
@Getter
@AllArgsConstructor
public class OrderListDto {

  private List<ShippingOrderDto> orders;
  private Integer total;

}

